---
- hosts: all
  name: Setup new system account
  become: yes
  tasks:
  - name: Create user
    user:
      name: "{{ user_name }}"
      shell: "{{ user_shell }}"
      password: "{{ user_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
      state: present
#      generate_ssh_key: "{{ user_ssh_bool }}"

